version: '3.8'

services:
  fastapi:
   build:
    context: ./project/backend
    dockerfile: Dockerfile
   command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
   volumes:
     - ./project/backend:/usr/src
   ports:
     - 8000:8000