version: '3.8'

services:
  fastapi:
   build:
    context: ./project/backend
    dockerfile: Dockerfile
   command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
   volumes:
     - ./project/backend:/usr/src
   ports:
     - 8000:8000
  mysql:
   image: mysql:8.0
   environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: 'googleserachapp'
    TZ: 'Asia/Tokyo'
   volumes:
     - mysql_data:/var/lib/mysql
   command: --default-authentication-plugin=mysql_native_password
   ports:
     - '33306:3306'

volumes:
  mysql_data: